apiVersion: v1
kind: Service
metadata:
  name: frepo-dev-service
  namespace: fieldeagles
  labels:
    service: frepo-dev-service
spec:
  type: NodePort
  ports:
    - name: http
      port: 80
      targetPort: dev-port
      nodePort: 30123
      protocol: TCP
  selector:
    app: frepo-dev
  
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: frepo-dev
  namespace: fieldeagles
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: frepo-dev
    spec:
      imagePullSecrets:
      - name: dockerhub-raksan
      containers:
      - name: frepo-dev
        image: dockerhub.raksan.in/fieldeagles/fieldrepo:dev-78
        imagePullPolicy: IfNotPresent
        ports:
        - name: dev-port
          containerPort: 80
          protocol: TCP
        env:
        - name: MONGO_URL
          value: mongodb://mongo.fieldeagles:27017/frepo_dev
        - name: SETTINGS_FILE
          value: /home/meteor/www/settings.json
        - name: ROOT_URL
          value:  https://dev.fieldrepo.com
