apiVersion: v1
kind: PersistentVolume
metadata:
  name: gluster-pv
  namespace: fieldeagles   
spec:
  capacity:
    storage: 900Gi     
  accessModes:
  - ReadWriteMany    
  glusterfs:         
    endpoints: glusterfs-cluster 
    path: /glustervol1 
    readOnly: false
  persistentVolumeReclaimPolicy: Retain 
  storageClassName: gfs
