apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gluster-claim
  namespace: fieldeagles  
spec:
  storageClassName: gfs
  accessModes:
  - ReadWriteMany      
  resources:
     requests:
       storage: 100Gi